# ClusterSecretStore tells the External Secrets Operator which secret backend
# to use and how to authenticate. This one uses GCP Secret Manager with
# Workload Identity (no static credentials).
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: traffic-priority-ahan
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: traffic-priority-cluster
          clusterProjectID: traffic-priority-ahan
          serviceAccountRef:
            name: secret-accessor
            namespace: default
